### PR TITLE
Add py38 to tox and travis

### PR DESCRIPTION
**Pull request by clbarnes**
Can wait until after the windows tests go in.

### CODE REVIEW

**Comment by clbarnes** [comment]
Although maybe this has somehow prevented travis from detecting the config at all? It doesn't seem to be running. `tox` works locally though.

**Comment by aaronshifman** [comment]
Is travis active it doesn't seem to be checking any of the PRs?

**Comment by clbarnes** [comment]
Up, apparently https://www.traviscistatus.com/ :man_shrugging:

**Comment by aaronshifman** [comment]
Sorry I meant is the repo linked to Travis - I don't have config access so I can't check

**Comment by psilentp** [comment]
@clbarnes I should have pinged you in #54 since you did all the work to get the tests running. I set up the CI with github actions since: 
1. it doesn't require maintaining a separate account 
2. maybe better windows support. 

Mostly 1. since the last point is totally speculative on the current ownership. Happy to switch things over to travis - but I think we should probably stick with one CI pipeline.

**Comment by clbarnes** [comment]
Ah yes, I see now. I'm in favour of sticking to one CI pipeline if it lets us share config between OSs, which it seems to! I haven't used github actions before. I'll scrap this PR. If you haven't already, you could delete `.travis.yml` in your PR and then we can add 3.8 to that, probably best as a separate PR after it's been merged.

**Pull request closed without merging**
